spring.application.name=demospring
server.port=8080
spring.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.auto-index-creation=true
spring.config.import=optional:file:.env[.properties]
spring.security.user.name=${USER}
spring.security.user.password=${PASSWORD}